openapi: '3.0.3'
info:
  version: 1.0.0
  title: User API for Rakuten Mobile test
  termsOfService: https://swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org
  contact:
    name: kenny.karnama
    email: kennykarnama@gmail.com
servers:
  - url: http://localhost:8080
    description: local environment
paths:
  /validate:
    get:
      tags:
        - "User API"
      summary: Validate user
      description: ''
      security:
        - basicAuth: []
      responses:
        '200':
          description: User detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          description: Internal server errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /register:
    post:
      tags:
        - "User API"
      summary: Register a new user
      description: ''
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: New user created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error. Error message will be hidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '415':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    User:
      type: object
      required:
        - user_id
        - name
      properties:
        user_id:
          type: string
        name:
          type: string
        role:
          type: string
          default: "USER"
        created_at:
          type: string
          format: date-time
    RegisterRequest:
      type: object
      required:
        - name
        - password
      properties:
        name:
          type: string
          minLength: 5
          maxLength: 255
        password:
          type: string
          minLength: 4
    ErrorResponse:
      type: object
      properties:
        error_code:
          type: int
          format: int64
        error_message:
          type: string
